name: "Docusaurus 🦖 GitHub Pages"

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 21
      
      - name: Build Docusaurus website
        run: |
          npm install 
          npm run build

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
